---
title: "data-processing"
author: "Ashley Asmus"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(janitor)
library(tidyverse)
library(plotly)
# remotes::install_github("Metropolitan-Council/councilR")
library(councilR)
library(cowplot)
library(magick)
library(ggtext)
library(showtext)

font_add("HelveticaNeueLTStd", "HelveticaNeueLTStd-Lt.otf")
font_add("Arial Narrow", "Arial Narrow.ttf")
font_add("Arial Narrow Italic",
         regular = "Arial Narrow.ttf",
         italic = "Arial Narrow Italic.ttf"
)
showtext_auto()
```

## Read in raw data from Excel
### copy data
```{r load}
raw_load_data <- read_excel("data/raw-load-data.xlsx",
                            col_types = c(
                              "text", "skip", "skip",
                              "date", "skip", "numeric", "numeric",
                              "skip", "skip", "skip", "numeric",
                              "skip", "skip", "skip", "skip", "skip",
                              "skip", "skip", "skip", "skip"
                            ),
                            skip = 1
) %>%
  janitor::clean_names() %>%
  mutate(sample_start_date = as.Date(sample_start_date))
```

### Variant data
```{r variants}
header1 <- read.csv('data/raw-variant-data.csv') %>% names()
header2 <- read.csv('data/raw-variant-data.csv', skip = 1) %>% names()
header <- paste0(header1, header2) 

raw_variant_data <- read.csv(
 'data/raw-variant-data.csv', skip = 1
) %>%
  set_names(header) %>%
  janitor::clean_names() %>%
  select(-l452r_sample_start_date_1, -k417n_sample_start_date_2) %>%
  rename(l452r_sample_id = l452r_1sample, 
         k417n_sample_id = k417n_1sample_1) %>%
  rename(n501y_frequency= n501y_1frequency_of_mutant_allele, 
         l452r_frequency = l452r_2frequency_of_mutant_allele_1,
         k417n_frequency = k417n_2frequency_of_mutant_allele_2) %>%
  rename(date = i_n501y_sample_start_date) 

variant_samples <- raw_variant_data %>%
  select(date, contains('sample_id')) %>%
  pivot_longer(contains('sample_id'), names_to = 'mutation', values_to = 'sample_id') %>%
  mutate(mutation = str_remove(mutation, '_sample_id'))


variant_frequencies <- raw_variant_data %>%
  select(date, contains('frequency')) %>%
  pivot_longer(contains('frequency'), names_to = 'mutation', values_to = 'frequency') %>%
  mutate(mutation = str_remove(mutation, '_frequency'))


variant_data <- merge(variant_samples, variant_frequencies)
```

### case load from USA Facts
```{r}
raw_case_data <- read.csv('https://static.usafacts.org/public/data/covid-19/covid_confirmed_usafacts.csv?_ga=2.86006619.233414847.1642517751-2016304881.1642174657')

case_data <- raw_case_data %>%
  janitor::clean_names() %>%
  filter(county_name %in% c('Hennepin County ', 'Ramsey County ', 'Scott County ', 'Dakota County ', 'Washington County ', 'Anoka County ', 'Carver County ') & state == 'MN') %>%
  select(-county_fips, -state, -state_fips)%>%
  pivot_longer(cols = contains("x"), names_to = 'date', values_to = 'covid_cases_total') %>%
  mutate(date = str_remove(date, "x")) %>%
  mutate(date = as.Date(date, format = "%Y_%m_%d")) %>%
  group_by(date) %>%
  summarize(covid_cases_total = sum(covid_cases_total)) %>%
  mutate(covid_cases_new = covid_cases_total - lag(covid_cases_total,1)) %>%
  mutate(covid_cases_per100K = 100000*covid_cases_new/(3163104)) %>%
  # mutate(frequency_gapfill = zoo::na.approx(frequency, maxgap = 2, na.rm = F)) %>%
  # now getting a rolling average with a 7-day window: 
  mutate(covid_cases_7day = zoo::rollapply(covid_cases_per100K, 7, align = "right", mean, na.rm = T, partial = T, fill = NA)) %>%
  mutate(hover_text_case = paste0(format(date, "%b %d, %Y"), "<br>",
                             "<b>", round(covid_cases_7day, 2), "</b> cases per 100,000 people") )
```


## Cacluate load  
```{r load reshape}
seq_date <- function(x) seq(min(x, na.rm = T), max(x, na.rm = T), by = "day")
all_dates <- seq_date(raw_load_data$sample_start_date)

load_data <-
  raw_load_data %>%
  mutate(flow_l_day = metro_flow_rate_mgd_on_sample_start_date * 3785411.8) %>%
  select(-metro_flow_rate_mgd_on_sample_start_date) %>%
  rename(N1_gene_l = copies_l_3, N2_gene_l = copies_l_4) %>%
  pivot_longer(
    cols = c("N1_gene_l", "N2_gene_l"), names_to = "gene_num",
    values_to = "n_l"
  ) %>%
  # calculate n per day, per person, per person in millions
  mutate(copies_day = n_l * flow_l_day) %>%
  mutate(copies_day_person = copies_day / 195000) %>%
  mutate(copies_day_person_M = copies_day_person / 1e7) %>%
  # average across runs for a sample average
  group_by(sample_name, sample_start_date, flow_l_day) %>%
  summarize(across(c(copies_day_person_M), ~ mean(., na.rm = T))) %>%
  ungroup() %>%
  # average by date:
  group_by(sample_start_date) %>%
  add_tally(name = "n_samples") %>%
  summarize(
    copies_day_person_M_mn = mean(copies_day_person_M, na.rm = T),
    copies_day_person_M_se = sd(copies_day_person_M, na.rm = T) / (n_samples)
  ) %>%
  ungroup() %>%
  unique() %>%
  rename(date = sample_start_date) %>%
  # calculate a rolling 7 day average
  # (fill in for missing dates)
  complete(date = seq.Date(min(date, na.rm = T), max(date, na.rm = T), by = "days")) %>%
  arrange(date) %>%
  mutate(hover_text_load = paste0(
    format(date, "%b %d, %Y"), "<br>",
    "<b>", round(copies_day_person_M_mn, 2), "</b> copies of RNA per day per person"
  ))

head(load_data)
tail(load_data)
```


## Graph of load and cases  

```{r load-graph-large}
ylim.cases <- c(0, max(case_data$covid_cases_7day, na.rm = T))
ylim.load <- c(0, max(load_data$copies_day_person_M_mn, na.rm = T))

b <- diff(ylim.cases) / diff(ylim.load)
library(ggtext)
# Graph of load
load_plot <-
  load_data %>%
  left_join(case_data) %>%
  filter(date >= "2021-06-01") %>%
  ggplot(aes(x = date, y = copies_day_person_M_mn)) +
  geom_ribbon(
    aes(ymin = 0, ymax = covid_cases_7day / b),
    fill = colors$suppGray,
    alpha = 0.3,
    na.rm = T,
    linetype = "blank"
  ) +
  geom_line(
    aes(y = copies_day_person_M_mn),
    color = colors$councilBlue,
    alpha = 0.8,
    lwd = 1.2,
    na.rm = T
  ) +
  #   geom_point(
  #   aes(y = copies_day_person_M_mn),
  #   color = colors$councilBlue,
  #   alpha = 0.8,
  #   lwd = 1.2,
  #   na.rm = T
  # ) +
  scale_y_continuous(
    "COVID-19 cases per 100,000 residents (7-day avg.)",
    sec.axis = sec_axis(
      ~ . * b,
      name = "Viral load (M copies per person, per day)",
      breaks = seq(from = 0, to = 150, by = 25)
    )
  ) +
  labs(
    title = "<span style='color:#0054A4;'>Viral load in wastewater</span>
    compared to <span style='color:#888888;'>metro-area COVID-19 cases</span>",
    x = "Date",
    caption = paste0(
      "\nCase data (gray area) are seven-day rolling averages for the 7-county area provided by MDH\nand downloaded from USAFacts. Viral load (blue line) are daily data.\nLast sample date ",
      max(load_data$date, na.rm = T),
      "."
    )
  ) +
  scale_x_date(date_breaks = "month", date_labels = "%b '%y") +
  councilR::council_theme(use_showtext = TRUE) +
  theme(
    axis.title.y.left = element_text(color = "#888888", vjust = 1),
    axis.title.y.right = element_text(color = colors$councilBlue, vjust = 1),
    axis.text.y.left = element_text(color = "#888888", vjust = 0),
    axis.text.y.right = element_text(color = colors$councilBlue, vjust = 0),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_markdown(lineheight = 1.1,
                                  size = 18, hjust = 0.5),
    plot.caption = element_text(
      size = 10,
      face = "italic",
      family = "Arial Narrow Italic"
    ),
  )

load_plot

ggsave("fig/cases_vs_load_large.png", 
       load_plot, height = 8.5, width =11,
       units = "in", dpi = 300)
```


```{r loag-graph-small}

load_data %>%
  left_join(case_data) %>%
  filter(date >= "2021-06-01") %>%
  ggplot(aes(x = date, y = copies_day_person_M_mn)) +
  geom_ribbon(
    aes(ymin = 0, ymax = covid_cases_7day / b),
    fill = colors$suppGray,
    alpha = 0.3,
    na.rm = T,
    linetype = "blank"
  ) +
  geom_line(
    aes(y = copies_day_person_M_mn),
    color = colors$councilBlue,
    alpha = 0.8,
    lwd = 0.25,
    na.rm = T
  ) +
  scale_y_continuous(
    "COVID-19 cases per 100,000 residents (7-day avg.)",
    sec.axis = sec_axis(
      ~ . * b,
      name = "Viral load (M copies per person, per day)",
      breaks = seq(from = 0, to = 150, by = 25)
    )
  ) +
  labs(
    title = "<span style='color:#0054A4;'>Viral load in wastewater</span>
    compared to <span style='color:#888888;'>metro-area COVID-19 cases</span>",
    x = "Date",
    caption = paste0(
      "\nCase data (gray area) are seven-day rolling averages for the 7-county area provided by MDH\nand downloaded from USAFacts. Viral load (blue line) are daily data.\nLast sample date ",
      max(load_data$date, na.rm = T),
      "."
    )
  ) +
  scale_x_date(date_breaks = "month", date_labels = "%b '%y")  +
  council_theme(size_header = 7,
                size_axis_text = 5,
                size_axis_title = 6,
                size_caption = 3,
                use_showtext = T) +
  theme(plot.title = element_markdown(lineheight = 1.1,
                                      size = 7, hjust = 0.5),
        axis.title.y.left = element_text(color = "#888888", vjust = 1),
        axis.title.y.right = element_text(color = colors$councilBlue, vjust = 1),
        axis.text.y.left = element_text(color = "#888888", vjust = 0),
        axis.text.y.right = element_text(color = colors$councilBlue, vjust = 0),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(
          size = 3,
          face = "italic",
          family = "Arial Narrow Italic"
        )
  )

ggsave("fig/cases_vs_load_small.png", 
       height = 675, width = 1200,
       units = "px", dpi = 300)
```


## Reshape variant data  

```{r variant proportion}
variant_data_new <-
  variant_data %>%
  mutate(date = as.Date(date, format = "%m/%d/%Y")) %>%
  # average by date
  group_by(date, mutation) %>%
  summarize(frequency = mean(frequency, na.rm = T)) %>%
  ungroup() %>%
  mutate(variant = case_when(
    mutation == "n501y" ~ "Alpha, Beta & Gamma",
    mutation == "l452r" ~ "Delta",
    mutation == "k417n" & date >= "2021-11-18" ~ "Omicron",
    TRUE ~ "Other"
  )) %>%
  mutate(mutation = toupper(mutation)) %>%
  # rolling 7 day average, by variant type
  complete(nesting(mutation, variant),
           date = seq.Date(min(date, na.rm = T), max(date, na.rm = T), by = "days")
  ) %>%
  group_by(mutation, variant) %>%
  # interpolate missing values up to 3 days:
  mutate(frequency_gapfill = zoo::na.approx(frequency, maxgap = 2, na.rm = F)) %>%
  # now getting a rolling average with a 7-day window:
  mutate(frequency_7day = zoo::rollapply(frequency_gapfill, 7, align = "center", mean, na.rm = T, partial = T, fill = NA)) %>%
  ungroup() %>%
  arrange(date, mutation, variant) %>%
  filter(!variant == "Other") %>%
  mutate(hover_text_variant = paste0(
    format(date, "%b %d, %Y"), "<br>",
    "<b>", variant, "</b> ", round(frequency_7day * 100, digits = 2), "%"
  ))
# View(variant_data)
```



## Graph of variants  


```{r variant-plot-large}
# variant_plot<-
varplot <-
  variant_data_new %>%
  filter(!variant == "Other") %>%
  filter(date >= "2021-06-01") %>%
  ggplot(aes(x = date, y = frequency, color = variant, fill = variant)) +
  geom_line(aes(x = date, y = frequency_7day, color = variant), size = 0.8) +
  geom_area(position = "identity", aes(x = date, y = frequency_7day, group = variant, fill = variant, color = variant), alpha = 0.25, na.rm = T, lty = "blank") +
  geom_point() +
  scale_color_manual(
    values = c("#84BB25", "#1D94B7", "#6D3571"),
    name = "Variant "
  ) +
  scale_fill_manual(values = c("#84BB25", "#1D94B7", "#6D3571"), 
                    name = "Variant ") +
  scale_y_continuous(name = "Variant frequency (%)", labels = scales::percent, limits = c(0, 1.05)) +
  scale_x_date(name = "Date", breaks = "1 months", date_labels = "%b '%y") +
  councilR::council_theme(use_showtext = T) +
  labs(
    title = "COVID-19 Variants in Metro Plant Wastewater",
    caption = paste0("\nShaded areas and lines are seven-day rolling averages. Points are daily data.\nLast sample date ", max(variant_data_new$date, na.rm = T), ".")
  ) +
  # theme_minimal() +
  council_theme(use_showtext = T) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.caption = element_text(
      size = 11,
      face = "italic",
      margin = margin(t = -15, 0,0,0),
      family = "Arial Narrow Italic"
    ),
    legend.justification = c(0,0),
    legend.text = element_text(size = 12),
    
  )

varplot

logo_file <- "metc-wastewater-covid-monitor/www/main-logo.png"

ggsave("fig/variants_static_graph_large.png",
       varplot,
       width = 11,
       height = 8.5,
       dpi = 300
)
```


```{r variant-plot-small}
# variant_plot<-

variant_data_new %>%
  filter(!variant == "Other",
         date >= "2021-06-01") %>%
  ggplot(aes(x = date, y = frequency, color = variant, fill = variant)) +
  geom_line(aes(x = date, y = frequency_7day, color = variant), 
            # size = 0.8,
            lwd = 0.3) +
  geom_area(position = "identity", aes(x = date, 
                                       y = frequency_7day,
                                       group = variant,
                                       fill = variant, 
                                       color = variant),
            alpha = 0.25, na.rm = T, lty = "blank") +
  geom_point(size = 0.1) +
  scale_color_manual(
    values = c("#84BB25", "#1D94B7", "#6D3571"),
    name = "Variant "
  ) +
  scale_fill_manual(values = c("#84BB25", "#1D94B7", "#6D3571"), 
                    name = "Variant ") +
  scale_y_continuous(name = "Variant frequency (%)", 
                     labels = scales::percent, limits = c(0, 1.05)) +
  scale_x_date(name = "Date", breaks = "1 months", date_labels = "%b '%y") +
  labs(
    title = "COVID-19 Variants in Metro Plant Wastewater",
    caption = paste0("\nShaded areas and lines are seven-day rolling averages. Points are daily data.\nLast sample date ", max(variant_data_new$date, na.rm = T), ".")
  ) +
  council_theme(size_header = 7,
                size_axis_text = 5,
                size_axis_title = 6,
                size_caption = 3,
                size_legend_title = 4,
                size_legend_text = 3,
                use_showtext = T) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.caption = element_text(
      size = 3,
      # debug = T,
      face = "italic",
      family = "Arial Narrow Italic",
      margin = margin(t = -10, 0,0,0) 
    ),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.margin = margin(),
    legend.key.height = unit(10, "pt"),
    legend.justification = c(0,0),
    plot.title = element_text(hjust = 0.5)
    
  )


# logo_file <- "metc-wastewater-covid-monitor/www/main-logo.png"

ggsave("fig/variants_static_graph_small.png",
       height = 675, 
       width = 1200,
       dpi = 300,
       units = "px"
)
```


## Linear regression with cases
```{r}
```


## Write to .csv
```{r}

write.csv(case_data, "metc-wastewater-covid-monitor/data/case_data.csv", row.names = F)
write.csv(variant_data, "data/clean_variant_data.csv", row.names = F)
write.csv(variant_data, "metc-wastewater-covid-monitor/data/clean_variant_data.csv", row.names = F)
write.csv(load_data, "data/clean_load_data.csv", row.names = F)
write.csv(load_data, "metc-wastewater-covid-monitor/data/clean_load_data.csv", row.names = F)

# master dataset:
combined_data <-
  case_data %>%
  left_join(load_data, by = "date") %>%
  left_join(variant_data, by = "date")

write.csv(combined_data, "data/combined_data.csv", row.names = F)

write.csv(combined_data, "metc-wastewater-covid-monitor/data/combined_data.csv", row.names = F)
```
